### PR TITLE
Add buzzer

### PR DESCRIPTION
**Pull request by swstraus**
For your consideration:

I added code to set off a piezo alarm if the percentage drops below the defined alarm point.  I'm going to modify the housing so that a piezo can be mounted.  The ones I'm testing with are a little too big to be used on the hopper.

Having this code in place doesn't hurt anything if you aren't using a buzzer.

I'll modify the housing in fusion and send you the design and the stl if you want it.  The one I'm working with is for my dillon, so I'll update it to the correct diameter while I'm at it.  The Dillon hopper body is a little too tight (as some other folks have mentioned as well).

### CODE REVIEW

**Comment by nathandarnell** [comment]
Thanks for the commit!  I tested this and it works fine.  I like that the buzzer stops once you enter the menu with the tone() duration input.  



If you are able to find a small generic buzzer (the more common the better) I can see about modifying the housing to add it in since moving files from Onshape to Fusion 360 might be less than ideal.

At one point I had the idea of making something similar to Hornady's Lock-n-Load control panel:
1410992190-Control-Panel-Pistol-Bullet-Feeder-Closeup-PNG c745953e

Any interest in working on something similar?

**Comment by swstraus** [comment]
I like the idea of the lock-n-load control panel, but I don't think I could make use of it on my dillon, at least not the powder check part, as I have a 550, which doesn't have a powder check die.  On the 650, those components all have their own individual buzzers.  A central control panel showing all of the data is a neat idea.  The ESP8266 has a wifi chip.  Running a light http server on the things you want to track (like this powder measure) that just outputs state, and having another unit (like the lock-n-load) that reads that state and displays it from multiple devices on a larger TFT might actually be easier than cabling everything up.

Back to the buzzer, I made a sample with a couple of different mounting possibilities. Here's what I was thinking:

Screen Shot 2019-10-15 at 9 43 30 PM


One of them is a hole that's 11.8mm wide that the buzzer will press fit into.  You just push it in and it sits flush with the outside of the tube.

IMG_5829

On the other side is one with an 11.8mm wide depression 1mm deep into the wall.  The hole is 2.4mm wide in the center of that depression.  Thought there is that you could just glue the buzzer to the face of it.

Either will work, The bigger hole seems to work the best, maybe you have a better idea.  Any other buzzer I tried was just too big to fit on this.  I thought about making a little pedestal on the outside to mount a larger buzzer on and feeding the wire to the outside, but I think that would be kind of clunky.

**Comment by nathandarnell** [comment]
I like the idea of connecting individual sensors with wifi and I'll look into this.

The big bag of buzzers came and they work great.  Looking at your designs, the through-hole seems like the best option.  Thanks for working on that!  I edited the Hornady version with the hole on the lower right corner and have it printing now.  If it works I'll adjust the Dillon version for you to try out:

ModelWithBuzzerTop


ModelWithBuzzer

**Comment by swstraus** [comment]
You ready for me to try the Dillon one yet?

**Comment by nathandarnell** [comment]
Yep.  I tested it on my Hornady version this morning and everything fits fine:



Here is the Dillon model to try out:
[Dillon Main Body with Buzzer V1.4.stl.zip](https://github.com/nathandarnell/Reloading-Powder-Hopper-Level-Gauge-and-Alarm/files/3775267/Dillon.Main.Body.with.Buzzer.V1.4.stl.zip)

**Comment by swstraus** [comment]
I printed it out, haven't assembled it yet. Should there be a new bottom now that the ID of the main body has changed on the bottom?

**Comment by nathandarnell** [comment]
I didn't modify the bottom since the screw hole placement didn't change.  Let me know how it works!

**Comment by swstraus** [comment]
I got mine built, works great.  Out of curiosity, did you solder a 100 ohm resistor in line on the ground for your buzzer?

**Comment by nathandarnell** [comment]
I did not.  I tested it on a breadboard and didn't see any issues without it.  Did you use it and does it change the buzzer?

**Pull request merged**
